#!/usr/bin/ruby 
require 'optparse'

options = {
	:samplefile => nil,
	:dosage => false,
	:threshold => false 
}

OptionParser.new do |opts|
	opts.on( '-h', '--help', 'Display this screen' ) do
		puts opts
		exit
	end

	opts.on("-c", "--chr chrom", "chromosome") do |chrom|
		options[:chr] = chrom
	end 

	opts.on("-s", "--sample-file file","Sample file") do |file|
		options[:samplefile] = file
	end

	opts.on("-g", "--gen-file file", ".gen file") do |file|
		options[:genfile] = file
	end

	opts.on("-v", "--vcf-file file", ".vcf output file") do |file|
		options[:vcf_file] = file	
	end

	opts.on("-d", "--dosage", "Use dosage genotypes rather than genotype likelihoods as provided by IMPUTE2") do 
		options[:dosage] = true
	end

	opts.on("-t", "--threshold n", "Threshold likelihood to get genotype predictions" ) do |n|
		options[:threshold] = n
	end
end.parse!

puts options 

throw "Cannot do both dosage and threshold!" if options[:dosage] and options[:threshold]

# Read sample file:
samples = [] 
File.open(options[:samplefile]) do |file|
	lineno=0
	file.each do |line|
		lineno = lineno + 1
		next if lineno == 1
		samples << line.chomp.split(" ").first
	end
end

header = [ 
'##fileformat=VCFv4.1',
'##INFO=<ID=PSEUDO,Number=0,Type=Flag,Description="A dummy flag">',
'##FORMAT=<ID=GL,Number=.,Type=Float,Description="Genotype Likelihoods">'
].join("\n")

out = File.open(options[:vcf_file], "w")

out.puts(header)

fields = [
"#CHROM",
"POS",
"ID",
"REF",
"ALT",
"QUAL",
"FILTER",
"INFO",
"FORMAT",
] + samples 


# The Dosage represents the predicted dosage of the non reference allele given the data available, 
# it will always have a value between 0 and 2.
# The formula is Dosage = Pr(Het|Data) + 2*Pr(Alt|Data)
# See, http://www.1000genomes.org/faq/what-does-genotype-dosage-mean-phase1-integrated-call-set
def genotype_likelihoods_to_dosage(p_aa, p_ab, p_bb)
	p_bb * 2 + p_ab
end

out.puts(fields.join("\t"))

File.open(options[:genfile]) do |file|
	file.each do |line|
		vcfline = []
		fields = line.chomp.split(" ")
		vcfline << options[:chr] || fields[0]	# CHR
		vcfline << fields[2] 		# POS 
		vcfline << fields[1]		# ID
		vcfline << fields[3]		# REF allele 
		vcfline << fields[4]		# ALT allele 
		vcfline << 100			# QUAL (pseudo)
		vcfline << "PASS"		# FILTER (pseudo)
		vcfline << "PSEUDO=1"		# INFO (we do not use for anything)
		if options[:dosage] then
			vcfline << "DS"
		elsif options[:threshold] then
			vcfline << "GT"
		else
			vcfline << "GL"			# FORMAT 
		end
		likelihoods = []
		5.upto(fields.size-1) do |i|
			checkpoint = 7 % 3
			# Genotype likelihoods are required to be log10 scaled in VCF 
			if options[:dosage] or options[:threshold] then
				likelihoods << fields[i].to_f
			else 
				if fields[i].to_f == 0 then
					likelihoods << -100.0 # Suffiently small, but not -infinity
				else
					likelihoods << Math.log10(fields[i].to_f) 
				end
			end

			if i % 3 == checkpoint then
				if options[:dosage] then
					dosage = genotype_likelihoods_to_dosage(*likelihoods)
					genotype_likelihoods_to_dosage(*likelihoods)
					vcfline << dosage 
				elsif options[:threshold] then
					max_l = 0
					max_i = nil
					likelihoods.each_with_index do |l,i|
						if l > max_l then
							max_l = l
							max_i = i
						end
					end

					if max_l > options[:threshold].to_f then
						case max_i
							when 0
								vcfline << "0/0"
							when 1
								vcfline << "0/1"
							when 2
								vcfline << "1/1"
						end	
					else
						vcfline << "."
					end
				else
					vcfline << likelihoods.join(",")
				end
				likelihoods = []
			end
		end
		out.puts(vcfline.join("\t"))
	end
end

out.close
